[InputMethod]
Name=sitelen pona
LangCode=tok
Icon=
Addon=table
Configurable=True

[Table]
File=table/tok/tok.dict
OrderPolicy=None
AutoSelect=True
AutoSelectLength=1
Learning=False
ExactMatch=False
Hint=True
UseAlternativePageKey=True
FirstCandidateAsPreedit=True
CommitInvalidSegment=False

[Table/PrevPage]
0=Page_Up

[Table/NextPage]
0=Page_Down